using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Stove_Calculator.Models
{
    public class WireContext : DbContext
    {
        public DbSet<Wire> Wire { get; set; }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            => optionsBuilder.UseSqlite("Data Source=wire.db");

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Wire>().HasData(
                new Wire 
                { 
                    WireId = 1, 
                    Diameter = 0.1, 
                    Thickness = 0.1, 
                    IsRecommenderWidth1 = true, 
                    IsRecommenderWidth2 = true, 
                    IsRecommenderWidth4 = true,
                    IsRecommenderWidth6 = true,
                    IsRecommenderWidth8 = true,
                    IsRecommenderWidth10 = true,
                    IsRecommenderWidth12 = true,
                    IsRecommenderWidth14 = true,
                    IsRecommenderWidth16 = true,
                    IsRecommenderWidth18 = true,
                    IsRecommenderWidth20 = true,
                    IsRecommenderWidth25 = true,
                    IsRecommenderWidth30 = true,
                },
                new Wire
                {
                    WireId = 2,
                    Diameter = 0.2,
                    Thickness = 0.2,
                    IsRecommenderWidth1 = true,
                    IsRecommenderWidth2 = true,
                    IsRecommenderWidth4 = true,
                    IsRecommenderWidth6 = true,
                    IsRecommenderWidth8 = true,
                    IsRecommenderWidth10 = true,
                    IsRecommenderWidth12 = true,
                    IsRecommenderWidth14 = true,
                    IsRecommenderWidth16 = true,
                    IsRecommenderWidth18 = true,
                    IsRecommenderWidth20 = true,
                    IsRecommenderWidth25 = true,
                    IsRecommenderWidth30 = true,
                },
                new Wire
                {
                    WireId = 3,
                    Diameter = 0.3,
                    Thickness = 0.3,
                    IsRecommenderWidth1 = true,
                    IsRecommenderWidth2 = true,
                    IsRecommenderWidth4 = true,
                    IsRecommenderWidth6 = true,
                    IsRecommenderWidth8 = true,
                    IsRecommenderWidth10 = true,
                    IsRecommenderWidth12 = true,
                    IsRecommenderWidth14 = true,
                    IsRecommenderWidth16 = true,
                    IsRecommenderWidth18 = true,
                    IsRecommenderWidth20 = true,
                    IsRecommenderWidth25 = true,
                    IsRecommenderWidth30 = true,
                },
                new Wire
                {
                    WireId = 4,
                    Diameter = 0.4,
                    Thickness = 0.4,
                    IsRecommenderWidth1 = true,
                    IsRecommenderWidth2 = true,
                    IsRecommenderWidth4 = true,
                    IsRecommenderWidth6 = true,
                    IsRecommenderWidth8 = true,
                    IsRecommenderWidth10 = true,
                    IsRecommenderWidth12 = true,
                    IsRecommenderWidth14 = true,
                    IsRecommenderWidth16 = true,
                    IsRecommenderWidth18 = true,
                    IsRecommenderWidth20 = true,
                    IsRecommenderWidth25 = true,
                    IsRecommenderWidth30 = true,
                },
                new Wire
                {
                    WireId = 5,
                    Diameter = 0.5,
                    Thickness = 0.5,
                    IsRecommenderWidth1 = true,
                    IsRecommenderWidth2 = true,
                    IsRecommenderWidth4 = true,
                    IsRecommenderWidth6 = true,
                    IsRecommenderWidth8 = true,
                    IsRecommenderWidth10 = true,
                    IsRecommenderWidth12 = true,
                    IsRecommenderWidth14 = true,
                    IsRecommenderWidth16 = true,
                    IsRecommenderWidth18 = true,
                    IsRecommenderWidth20 = true,
                    IsRecommenderWidth25 = true,
                    IsRecommenderWidth30 = true,
                },
                new Wire
                {
                    WireId = 6,
                    Diameter = 0.6,
                    Thickness = 0.6,
                    IsRecommenderWidth1 = false,
                    IsRecommenderWidth2 = true,
                    IsRecommenderWidth4 = true,
                    IsRecommenderWidth6 = true,
                    IsRecommenderWidth8 = true,
                    IsRecommenderWidth10 = true,
                    IsRecommenderWidth12 = true,
                    IsRecommenderWidth14 = true,
                    IsRecommenderWidth16 = true,
                    IsRecommenderWidth18 = true,
                    IsRecommenderWidth20 = true,
                    IsRecommenderWidth25 = true,
                    IsRecommenderWidth30 = true,
                },
                new Wire
                {
                    WireId = 7,
                    Diameter = 0.7,
                    Thickness = 0.7,
                    IsRecommenderWidth1 = false,
                    IsRecommenderWidth2 = true,
                    IsRecommenderWidth4 = true,
                    IsRecommenderWidth6 = true,
                    IsRecommenderWidth8 = true,
                    IsRecommenderWidth10 = true,
                    IsRecommenderWidth12 = true,
                    IsRecommenderWidth14 = true,
                    IsRecommenderWidth16 = true,
                    IsRecommenderWidth18 = true,
                    IsRecommenderWidth20 = true,
                    IsRecommenderWidth25 = true,
                    IsRecommenderWidth30 = true,
                },
                new Wire
                {
                    WireId = 8,
                    Diameter = 0.8,
                    Thickness = 0.8,
                    IsRecommenderWidth1 = false,
                    IsRecommenderWidth2 = true,
                    IsRecommenderWidth4 = true,
                    IsRecommenderWidth6 = true,
                    IsRecommenderWidth8 = true,
                    IsRecommenderWidth10 = true,
                    IsRecommenderWidth12 = true,
                    IsRecommenderWidth14 = true,
                    IsRecommenderWidth16 = true,
                    IsRecommenderWidth18 = true,
                    IsRecommenderWidth20 = true,
                    IsRecommenderWidth25 = true,
                    IsRecommenderWidth30 = true,
                },
                new Wire
                {
                    WireId = 9,
                    Diameter = 0.9,
                    Thickness = 0.9,
                    IsRecommenderWidth1 = false,
                    IsRecommenderWidth2 = true,
                    IsRecommenderWidth4 = true,
                    IsRecommenderWidth6 = true,
                    IsRecommenderWidth8 = true,
                    IsRecommenderWidth10 = true,
                    IsRecommenderWidth12 = true,
                    IsRecommenderWidth14 = true,
                    IsRecommenderWidth16 = true,
                    IsRecommenderWidth18 = true,
                    IsRecommenderWidth20 = true,
                    IsRecommenderWidth25 = true,
                    IsRecommenderWidth30 = true,
                },
                new Wire
                {
                    WireId = 10,
                    Diameter = 1.0,
                    Thickness = 1.0,
                    IsRecommenderWidth1 = false,
                    IsRecommenderWidth2 = true,
                    IsRecommenderWidth4 = true,
                    IsRecommenderWidth6 = true,
                    IsRecommenderWidth8 = true,
                    IsRecommenderWidth10 = true,
                    IsRecommenderWidth12 = true,
                    IsRecommenderWidth14 = true,
                    IsRecommenderWidth16 = true,
                    IsRecommenderWidth18 = true,
                    IsRecommenderWidth20 = true,
                    IsRecommenderWidth25 = true,
                    IsRecommenderWidth30 = true,
                },
                new Wire
                {
                    WireId = 11,
                    Diameter = 1.1,
                    Thickness = 1.1,
                    IsRecommenderWidth1 = false,
                    IsRecommenderWidth2 = false,
                    IsRecommenderWidth4 = true,
                    IsRecommenderWidth6 = true,
                    IsRecommenderWidth8 = true,
                    IsRecommenderWidth10 = true,
                    IsRecommenderWidth12 = true,
                    IsRecommenderWidth14 = true,
                    IsRecommenderWidth16 = true,
                    IsRecommenderWidth18 = true,
                    IsRecommenderWidth20 = true,
                    IsRecommenderWidth25 = true,
                    IsRecommenderWidth30 = true,
                },
                new Wire
                {
                    WireId = 12,
                    Diameter = 1.2,
                    Thickness = 1.2,
                    IsRecommenderWidth1 = false,
                    IsRecommenderWidth2 = false,
                    IsRecommenderWidth4 = true,
                    IsRecommenderWidth6 = true,
                    IsRecommenderWidth8 = true,
                    IsRecommenderWidth10 = true,
                    IsRecommenderWidth12 = true,
                    IsRecommenderWidth14 = true,
                    IsRecommenderWidth16 = true,
                    IsRecommenderWidth18 = true,
                    IsRecommenderWidth20 = true,
                    IsRecommenderWidth25 = true,
                    IsRecommenderWidth30 = true,
                },
                new Wire
                {
                    WireId = 13,
                    Diameter = 1.4,
                    Thickness = 1.4,
                    IsRecommenderWidth1 = false,
                    IsRecommenderWidth2 = false,
                    IsRecommenderWidth4 = true,
                    IsRecommenderWidth6 = true,
                    IsRecommenderWidth8 = true,
                    IsRecommenderWidth10 = true,
                    IsRecommenderWidth12 = true,
                    IsRecommenderWidth14 = true,
                    IsRecommenderWidth16 = true,
                    IsRecommenderWidth18 = true,
                    IsRecommenderWidth20 = true,
                    IsRecommenderWidth25 = true,
                    IsRecommenderWidth30 = true,
                },
                new Wire
                {
                    WireId = 14,
                    Diameter = 1.6,
                    Thickness = 1.6,
                    IsRecommenderWidth1 = false,
                    IsRecommenderWidth2 = false,
                    IsRecommenderWidth4 = true,
                    IsRecommenderWidth6 = true,
                    IsRecommenderWidth8 = true,
                    IsRecommenderWidth10 = true,
                    IsRecommenderWidth12 = true,
                    IsRecommenderWidth14 = true,
                    IsRecommenderWidth16 = true,
                    IsRecommenderWidth18 = true,
                    IsRecommenderWidth20 = true,
                    IsRecommenderWidth25 = true,
                    IsRecommenderWidth30 = true,
                },
                new Wire
                {
                    WireId = 15,
                    Diameter = 1.8,
                    Thickness = 1.8,
                    IsRecommenderWidth1 = false,
                    IsRecommenderWidth2 = false,
                    IsRecommenderWidth4 = true,
                    IsRecommenderWidth6 = true,
                    IsRecommenderWidth8 = true,
                    IsRecommenderWidth10 = true,
                    IsRecommenderWidth12 = true,
                    IsRecommenderWidth14 = true,
                    IsRecommenderWidth16 = true,
                    IsRecommenderWidth18 = true,
                    IsRecommenderWidth20 = true,
                    IsRecommenderWidth25 = true,
                    IsRecommenderWidth30 = true,
                },
                new Wire
                {
                    WireId = 16,
                    Diameter = 2.0,
                    Thickness = 2.0,
                    IsRecommenderWidth1 = false,
                    IsRecommenderWidth2 = false,
                    IsRecommenderWidth4 = true,
                    IsRecommenderWidth6 = true,
                    IsRecommenderWidth8 = true,
                    IsRecommenderWidth10 = true,
                    IsRecommenderWidth12 = true,
                    IsRecommenderWidth14 = true,
                    IsRecommenderWidth16 = true,
                    IsRecommenderWidth18 = true,
                    IsRecommenderWidth20 = true,
                    IsRecommenderWidth25 = true,
                    IsRecommenderWidth30 = true,
                },
                new Wire
                {
                    WireId = 17,
                    Diameter = 2.2,
                    Thickness = 2.2,
                    IsRecommenderWidth1 = false,
                    IsRecommenderWidth2 = false,
                    IsRecommenderWidth4 = true,
                    IsRecommenderWidth6 = true,
                    IsRecommenderWidth8 = true,
                    IsRecommenderWidth10 = true,
                    IsRecommenderWidth12 = true,
                    IsRecommenderWidth14 = true,
                    IsRecommenderWidth16 = true,
                    IsRecommenderWidth18 = true,
                    IsRecommenderWidth20 = true,
                    IsRecommenderWidth25 = true,
                    IsRecommenderWidth30 = true,
                },
                new Wire
                {
                    WireId = 18,
                    Diameter = 2.5,
                    Thickness = 2.5,
                    IsRecommenderWidth1 = false,
                    IsRecommenderWidth2 = false,
                    IsRecommenderWidth4 = true,
                    IsRecommenderWidth6 = true,
                    IsRecommenderWidth8 = true,
                    IsRecommenderWidth10 = true,
                    IsRecommenderWidth12 = true,
                    IsRecommenderWidth14 = true,
                    IsRecommenderWidth16 = true,
                    IsRecommenderWidth18 = true,
                    IsRecommenderWidth20 = true,
                    IsRecommenderWidth25 = true,
                    IsRecommenderWidth30 = true,
                },
                new Wire
                {
                    WireId = 19,
                    Diameter = 2.8,
                    Thickness = 2.8,
                    IsRecommenderWidth1 = false,
                    IsRecommenderWidth2 = false,
                    IsRecommenderWidth4 = true,
                    IsRecommenderWidth6 = true,
                    IsRecommenderWidth8 = true,
                    IsRecommenderWidth10 = true,
                    IsRecommenderWidth12 = true,
                    IsRecommenderWidth14 = true,
                    IsRecommenderWidth16 = true,
                    IsRecommenderWidth18 = true,
                    IsRecommenderWidth20 = true,
                    IsRecommenderWidth25 = true,
                    IsRecommenderWidth30 = true,
                },
                new Wire
                {
                    WireId = 20,
                    Diameter = 3.0,
                    Thickness = 3.0,
                    IsRecommenderWidth1 = false,
                    IsRecommenderWidth2 = false,
                    IsRecommenderWidth4 = true,
                    IsRecommenderWidth6 = true,
                    IsRecommenderWidth8 = true,
                    IsRecommenderWidth10 = true,
                    IsRecommenderWidth12 = true,
                    IsRecommenderWidth14 = true,
                    IsRecommenderWidth16 = true,
                    IsRecommenderWidth18 = true,
                    IsRecommenderWidth20 = true,
                    IsRecommenderWidth25 = true,
                    IsRecommenderWidth30 = true,
                }
                );
        }
    }

}
